FROM arm64v8/debian:13-slim
LABEL org.opencontainers.image.source=https://github.com/ondrejsika/counter-frontend-go
COPY counter-frontend-go /usr/local/bin
CMD [ "/usr/local/bin/counter-frontend-go" ]
EXPOSE 3000
